import type { Player } from "./types";

export interface WKBLTeam {
  id: string;
  name: string;
  shortName: string;
  color: string;
  rank: number;
  summary: string;
  league: "WKBL" | "KBL";
}

// 팀명 단축 상수 — TEAMS의 단일 진실. matches.ts 등에서 이걸 import해서 써야 함
export const TN = {
  WOORI:   "우리은행",
  HANA:    "하나원큐",
  SAMSUNG: "삼성생명",
  BNK:     "BNK",
  KB:      "KB",
  SHINHAN: "신한은행",
} as const;

export const TEAMS: WKBLTeam[] = [
  // ─── WKBL 여자농구 ────────────────────────────────────────
  { id: "woori",   name: "우리은행 우리WON",     shortName: "우리은행",  color: "#003DA5", rank: 1, summary: "리그 최강 수비 조직력",       league: "WKBL" },
  { id: "hana",    name: "하나원큐",              shortName: "하나원큐",  color: "#007B5F", rank: 2, summary: "공격 밸런스 좋은 상승세 팀",  league: "WKBL" },
  { id: "samsung", name: "삼성생명 블루밍스",     shortName: "삼성생명",  color: "#1428A0", rank: 3, summary: "수비 중심 조직력 팀",         league: "WKBL" },
  { id: "bnk",     name: "BNK 썸",                shortName: "BNK",       color: "#E31837", rank: 4, summary: "빠른 템포 역습 농구",         league: "WKBL" },
  { id: "kb",      name: "KB 스타즈",             shortName: "KB",        color: "#CB9E00", rank: 5, summary: "재건 중인 전통 강호",         league: "WKBL" },
  { id: "shinhan", name: "신한은행 에스버드",      shortName: "신한은행",  color: "#0046FF", rank: 6, summary: "젊은 선수 중심 팀",          league: "WKBL" },
  // ─── KBL 남자농구 ─────────────────────────────────────────
  { id: "sono",    name: "고양 소노 스카이거너스", shortName: "소노",      color: "#0B3D91", rank: 1, summary: "라건아 중심 압도적 골밑 농구", league: "KBL" },
  { id: "db",      name: "원주 DB 프로미",         shortName: "DB",        color: "#FF6B00", rank: 2, summary: "빠른 공수 전환과 팀 조직력",  league: "KBL" },
  { id: "sk",      name: "서울 SK 나이츠",         shortName: "SK",        color: "#E31837", rank: 3, summary: "허훈 중심 화려한 공격농구",   league: "KBL" },
  { id: "mobis",   name: "울산 현대모비스 피버스",  shortName: "모비스",    color: "#003DA5", rank: 4, summary: "전통의 강호, 탄탄한 수비",   league: "KBL" },
  { id: "kt",      name: "수원 KT 소닉붐",         shortName: "KT",        color: "#D10000", rank: 5, summary: "빠른 트랜지션 농구",         league: "KBL" },
  { id: "lg",      name: "창원 LG 세이커스",       shortName: "LG",        color: "#A50034", rank: 6, summary: "리빌딩 중인 전통 강호",       league: "KBL" },
];

export const PLAYERS: Player[] = [
  // ─── 우리은행 ────────────────────────────────────,
  {
    id: "woori-095450",
    name: "강계리",
    number: 1,
    position: "PG",
    height: "164cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095450.png?ver=241016",
    bio: {
      birth_year: 1993,
      age: 33,
      career_year: 12,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "안정감"],
    seasonStats: {"games":30,"mpg":21.3,"ppg":4.8,"rpg":2.8,"apg":2.5,"spg":0.7,"bpg":0.1,"fgPct":44.4,"threePct":21.1,"ftPct":51.7},
  },
  {
    id: "woori-096144",
    name: "최예원",
    number: 3,
    position: "SF",
    height: "178cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096144.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":2,"ppg":1,"rpg":2,"apg":0,"spg":0,"bpg":0,"fgPct":0,"threePct":0,"ftPct":50},
  },
  {
    id: "woori-095504",
    name: "김예진",
    number: 4,
    position: "SF",
    height: "174cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095504.png?ver=241016",
    bio: {
      birth_year: 1997,
      age: 29,
      career_year: 10,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑"],
    seasonStats: {"games":23,"mpg":14.8,"ppg":0.78,"rpg":2,"apg":0.3,"spg":0.4,"bpg":0.1,"fgPct":30,"threePct":13,"ftPct":50},
  },
  {
    id: "woori-095210",
    name: "심성영",
    number: 5,
    position: "PG",
    height: "165cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095210.png?ver=241016",
    bio: {
      birth_year: 1992,
      age: 34,
      career_year: 15,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "흐름 체인저"],
    seasonStats: {"games":23,"mpg":18,"ppg":4.96,"rpg":2,"apg":1.5,"spg":0.4,"bpg":0,"fgPct":40,"threePct":26.2,"ftPct":83.3},
  },
  {
    id: "woori-096145",
    name: "박소영",
    number: 6,
    position: "PG",
    height: "165cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096145.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":2,"ppg":2,"rpg":0,"apg":0,"spg":0,"bpg":0,"fgPct":0,"threePct":0,"ftPct":100},
  },
  {
    id: "woori-096005",
    name: "이민지",
    number: 7,
    position: "PG",
    height: "176cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096005.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["흐름 체인저"],
    seasonStats: {"games":24,"mpg":18.9,"ppg":7.46,"rpg":2.5,"apg":0.5,"spg":0.7,"bpg":0.2,"fgPct":34.3,"threePct":32.7,"ftPct":68.8},
  },
  {
    id: "woori-095707",
    name: "오승인",
    number: 8,
    position: "SF",
    height: "183cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095707.png?ver=241016",
    bio: {
      birth_year: 2000,
      age: 26,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":2.1,"ppg":0,"rpg":1,"apg":1,"spg":0,"bpg":0,"fgPct":0,"threePct":0,"ftPct":0},
  },
  {
    id: "woori-095528",
    name: "한엄지",
    number: 9,
    position: "SF",
    height: "180cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095528.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 9,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":2,"mpg":11.9,"ppg":3,"rpg":5,"apg":0.5,"spg":0,"bpg":0,"fgPct":50,"threePct":0,"ftPct":100},
  },
  {
    id: "woori-095444",
    name: "박혜미",
    number: 10,
    position: "SF",
    height: "182cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095444.png?ver=241016",
    bio: {
      birth_year: 1995,
      age: 31,
      career_year: 12,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑"],
    seasonStats: {"games":20,"mpg":11.6,"ppg":1.35,"rpg":1.5,"apg":0.2,"spg":0.1,"bpg":0.1,"fgPct":31.6,"threePct":13.8,"ftPct":37.5},
  },
  {
    id: "woori-095254",
    name: "유승희",
    number: 11,
    position: "PG",
    height: "175cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095254.png?ver=241016",
    bio: {
      birth_year: 1994,
      age: 32,
      career_year: 13,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑"],
    seasonStats: {"games":12,"mpg":11,"ppg":0.83,"rpg":1.9,"apg":0.8,"spg":0.6,"bpg":0,"fgPct":14.3,"threePct":13.3,"ftPct":100},
  },
  {
    id: "woori-096031",
    name: "오니즈카 아야노",
    number: 12,
    position: "PG",
    height: "168cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096031.png?ver=241016",
    bio: {
      birth_year: 1999,
      age: 27,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["1옵션", "슈터"],
    seasonStats: {"games":25,"mpg":23.6,"ppg":9.92,"rpg":2.4,"apg":0.8,"spg":1,"bpg":0.4,"fgPct":44.6,"threePct":38,"ftPct":62.5},
  },
  {
    id: "woori-095908",
    name: "변하정",
    number: 13,
    position: "SF",
    height: "180cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095908.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":28,"mpg":23.7,"ppg":3.11,"rpg":3.3,"apg":0.5,"spg":0.9,"bpg":0.4,"fgPct":44.4,"threePct":27.9,"ftPct":75},
  },
  {
    id: "woori-095703",
    name: "이명관",
    number: 20,
    position: "SF",
    height: "173cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095703.png?ver=241016",
    bio: {
      birth_year: 1996,
      age: 30,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["1옵션", "폭발력", "슈터"],
    seasonStats: {"games":23,"mpg":35.6,"ppg":11.57,"rpg":6.3,"apg":1.6,"spg":0.9,"bpg":0.1,"fgPct":35.8,"threePct":36.8,"ftPct":81},
  },
  {
    id: "woori-095909",
    name: "김솔",
    number: 21,
    position: "PG",
    height: "174cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095909.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "woori-095740",
    name: "편선우",
    number: 22,
    position: "SF",
    height: "178cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095740.png?ver=241016",
    bio: {
      birth_year: 2002,
      age: 24,
      career_year: 6,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":1.4,"ppg":0,"rpg":0,"apg":0,"spg":0,"bpg":1,"fgPct":0,"threePct":0,"ftPct":0},
  },
  {
    id: "woori-095104",
    name: "김단비",
    number: 23,
    position: "SF",
    height: "180cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095104.png?ver=241016",
    bio: {
      birth_year: 1990,
      age: 36,
      career_year: 18,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["베테랑", "MVP", "국가대표", "에이스", "폭발력", "수비형", "플레이메이커", "리바운더", "골밑 핵심"],
    seasonStats: {"games":30,"mpg":34.7,"ppg":18.33,"rpg":11.1,"apg":4.4,"spg":1.3,"bpg":1.1,"fgPct":41.8,"threePct":27,"ftPct":67.2},
  },
  {
    id: "woori-095742",
    name: "이다연",
    number: 24,
    position: "SF",
    height: "175cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095742.png?ver=241016",
    bio: {
      birth_year: 2001,
      age: 25,
      career_year: 6,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["흐름 체인저"],
    seasonStats: {"games":17,"mpg":22.6,"ppg":4.82,"rpg":4.2,"apg":0.5,"spg":0.6,"bpg":0.1,"fgPct":48.9,"threePct":20.5,"ftPct":100},
  },
  {
    id: "woori-096030",
    name: "세키 나나미",
    number: 77,
    position: "PG",
    height: "171cm",
    team: "우리은행 우리WON",
    teamId: "woori",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096030.png?ver=241016",
    bio: {
      birth_year: 2000,
      age: 26,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["흐름 체인저"],
    seasonStats: {"games":13,"mpg":21.7,"ppg":4.62,"rpg":2.6,"apg":1.7,"spg":0.5,"bpg":0.1,"fgPct":30.6,"threePct":17.4,"ftPct":46.2},
  },
  // ─── 하나원큐 ────────────────────────────────────,
  {
    id: "hana-096007",
    name: "하지윤",
    number: 0,
    position: "PG",
    height: "167cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096007.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":4,"mpg":5.5,"ppg":2,"rpg":0.8,"apg":1.3,"spg":1,"bpg":0.3,"fgPct":50,"threePct":50,"ftPct":0},
  },
  {
    id: "hana-095788",
    name: "박소희",
    number: 1,
    position: "PG",
    height: "178cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095788.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 5,
      national_team: { is_national: true, level: "국가대표 후보" },
    },
    tags: ["국가대표", "1옵션", "폭발력", "플레이메이커"],
    seasonStats: {"games":30,"mpg":29.4,"ppg":10.1,"rpg":3.6,"apg":3.5,"spg":0.4,"bpg":0.1,"fgPct":36.8,"threePct":29.8,"ftPct":84.7},
  },
  {
    id: "hana-096146",
    name: "황윤서",
    number: 2,
    position: "SF",
    height: "182cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096146.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":5,"mpg":4,"ppg":1.2,"rpg":0.2,"apg":0.2,"spg":0,"bpg":0,"fgPct":0,"threePct":66.7,"ftPct":0},
  },
  {
    id: "hana-096008",
    name: "정현",
    number: 3,
    position: "SF",
    height: "178cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096008.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":30,"mpg":27.3,"ppg":6.33,"rpg":3.4,"apg":1,"spg":0.6,"bpg":0.5,"fgPct":33,"threePct":33,"ftPct":62.9},
  },
  {
    id: "hana-095830",
    name: "고서연",
    number: 5,
    position: "PG",
    height: "172cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095830.png?ver=241016",
    bio: {
      birth_year: 2004,
      age: 22,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":27,"mpg":15.4,"ppg":2.93,"rpg":2,"apg":1.7,"spg":0.4,"bpg":0,"fgPct":44.8,"threePct":15.1,"ftPct":50},
  },
  {
    id: "hana-096147",
    name: "이은서",
    number: 6,
    position: "PG",
    height: "172cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096147.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":3,"mpg":5.8,"ppg":2,"rpg":1,"apg":0,"spg":0,"bpg":0,"fgPct":100,"threePct":0,"ftPct":0},
  },
  {
    id: "hana-095715",
    name: "정예림",
    number: 7,
    position: "PG",
    height: "175cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095715.png?ver=241016",
    bio: {
      birth_year: 2001,
      age: 25,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":29,"mpg":23.9,"ppg":3.9,"rpg":4.3,"apg":1.8,"spg":0.7,"bpg":0.7,"fgPct":42,"threePct":28.9,"ftPct":81.5},
  },
  {
    id: "hana-095442",
    name: "김시온",
    number: 9,
    position: "PG",
    height: "177cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095442.png?ver=241016",
    bio: {
      birth_year: 1995,
      age: 31,
      career_year: 12,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑"],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "hana-095259",
    name: "양인영",
    number: 11,
    position: "C",
    height: "184cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095259.png?ver=241016",
    bio: {
      birth_year: 1995,
      age: 31,
      career_year: 13,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["베테랑", "국가대표"],
    seasonStats: {"games":21,"mpg":10.8,"ppg":2.67,"rpg":2.4,"apg":0.9,"spg":0.5,"bpg":0.3,"fgPct":31.9,"threePct":0,"ftPct":83.3},
  },
  {
    id: "hana-096148",
    name: "김연진",
    number: 12,
    position: "SF",
    height: "176cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096148.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "hana-095041",
    name: "김정은",
    number: 13,
    position: "SF",
    height: "179cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095041.png?ver=241016",
    bio: {
      birth_year: 1987,
      age: 39,
      career_year: 20,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "안정감"],
    seasonStats: {"games":30,"mpg":18.2,"ppg":4.77,"rpg":4.5,"apg":1.7,"spg":0.3,"bpg":0.6,"fgPct":33.3,"threePct":20.3,"ftPct":51.7},
  },
  {
    id: "hana-095912",
    name: "이이지마 사키",
    number: 21,
    position: "SF",
    height: "173cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095912.png?ver=241016",
    bio: {
      birth_year: 1992,
      age: 34,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["에이스", "폭발력", "수비형", "슈터"],
    seasonStats: {"games":29,"mpg":32.5,"ppg":15.03,"rpg":6.3,"apg":2.3,"spg":1.5,"bpg":0.7,"fgPct":50.8,"threePct":35.3,"ftPct":80.4},
  },
  {
    id: "hana-095831",
    name: "이다현",
    number: 22,
    position: "SF",
    height: "179cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095831.png?ver=241016",
    bio: {
      birth_year: 2004,
      age: 22,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":11,"mpg":6.1,"ppg":2,"rpg":1.1,"apg":0.2,"spg":0,"bpg":0.3,"fgPct":45.5,"threePct":18.2,"ftPct":66.7},
  },
  {
    id: "hana-095832",
    name: "박진영",
    number: 23,
    position: "SF",
    height: "178cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095832.png?ver=241016",
    bio: {
      birth_year: 2004,
      age: 22,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":28,"mpg":16.1,"ppg":4.86,"rpg":2.1,"apg":0.6,"spg":0.3,"bpg":0.2,"fgPct":42.4,"threePct":34.4,"ftPct":70.4},
  },
  {
    id: "hana-095499",
    name: "진안",
    number: 31,
    position: "C",
    height: "182cm",
    team: "하나원큐",
    teamId: "hana",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095499.png?ver=241016",
    bio: {
      birth_year: 1996,
      age: 30,
      career_year: 10,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["베테랑", "국가대표", "1옵션", "폭발력", "리바운더", "골밑 핵심"],
    seasonStats: {"games":30,"mpg":30.9,"ppg":14.83,"rpg":9.3,"apg":2.7,"spg":0.7,"bpg":0.6,"fgPct":49.6,"threePct":0,"ftPct":60.2},
  },
  // ─── 삼성생명 ────────────────────────────────────,
  {
    id: "samsung-096028",
    name: "하마니시 나나미",
    number: 1,
    position: "PG",
    height: "168cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096028.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":27,"mpg":14.2,"ppg":3.41,"rpg":1.6,"apg":1.8,"spg":0.6,"bpg":0.1,"fgPct":39.3,"threePct":17.1,"ftPct":78.8},
  },
  {
    id: "samsung-095778",
    name: "이해란",
    number: 2,
    position: "SF",
    height: "182cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095778.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 5,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["MVP", "국가대표", "에이스", "폭발력", "수비형", "리바운더", "골밑 핵심"],
    seasonStats: {"games":30,"mpg":34.9,"ppg":17.4,"rpg":7.6,"apg":1.5,"spg":1.6,"bpg":1,"fgPct":48.5,"threePct":22.6,"ftPct":69.6},
  },
  {
    id: "samsung-095749",
    name: "조수아",
    number: 3,
    position: "PG",
    height: "170cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095749.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 6,
      national_team: { is_national: true, level: "국가대표 후보" },
    },
    tags: ["국가대표", "안정감"],
    seasonStats: {"games":29,"mpg":19.2,"ppg":5.14,"rpg":2.7,"apg":2.7,"spg":0.6,"bpg":0.1,"fgPct":33,"threePct":23.4,"ftPct":80.5},
  },
  {
    id: "samsung-095477",
    name: "김아름",
    number: 6,
    position: "SF",
    height: "174cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095477.png?ver=241016",
    bio: {
      birth_year: 1994,
      age: 32,
      career_year: 11,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "슈터", "안정감"],
    seasonStats: {"games":30,"mpg":22.5,"ppg":5.33,"rpg":3.8,"apg":1,"spg":0.6,"bpg":0.1,"fgPct":32.4,"threePct":35,"ftPct":73.7},
  },
  {
    id: "samsung-095713",
    name: "강유림",
    number: 7,
    position: "SF",
    height: "175cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095713.png?ver=241016",
    bio: {
      birth_year: 1997,
      age: 29,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["1옵션", "폭발력"],
    seasonStats: {"games":30,"mpg":33.4,"ppg":10,"rpg":4.6,"apg":1.5,"spg":1,"bpg":1,"fgPct":47.7,"threePct":23.6,"ftPct":86.8},
  },
  {
    id: "samsung-095524",
    name: "이주연",
    number: 8,
    position: "PG",
    height: "171cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095524.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 9,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["식스맨", "흐름 체인저"],
    seasonStats: {"games":19,"mpg":22.7,"ppg":6.37,"rpg":2.4,"apg":2.9,"spg":1,"bpg":0.2,"fgPct":44,"threePct":25.5,"ftPct":78.6},
  },
  {
    id: "samsung-096003",
    name: "유하은",
    number: 9,
    position: "SF",
    height: "178cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096003.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":18,"mpg":5.8,"ppg":0.83,"rpg":1.1,"apg":0.1,"spg":0.1,"bpg":0.1,"fgPct":37.5,"threePct":9.1,"ftPct":0},
  },
  {
    id: "samsung-096140",
    name: "양혜은",
    number: 10,
    position: "C",
    height: "178cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096140.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":1.9,"ppg":2,"rpg":1,"apg":0,"spg":0,"bpg":0,"fgPct":100,"threePct":0,"ftPct":0},
  },
  {
    id: "samsung-096139",
    name: "한지민",
    number: 12,
    position: "SF",
    height: "172cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096139.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":1.6,"ppg":0,"rpg":0,"apg":0,"spg":0,"bpg":0,"fgPct":0,"threePct":0,"ftPct":0},
  },
  {
    id: "samsung-095226",
    name: "김단비",
    number: 13,
    position: "SF",
    height: "175cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095226.png?ver=241016",
    bio: {
      birth_year: 1992,
      age: 34,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":7,"mpg":4.8,"ppg":0.43,"rpg":0.7,"apg":0.9,"spg":0.3,"bpg":0,"fgPct":0,"threePct":33.3,"ftPct":0},
  },
  {
    id: "samsung-095779",
    name: "임규리",
    number: 16,
    position: "SF",
    height: "183cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095779.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 5,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["국가대표"],
    seasonStats: {"games":3,"mpg":3.1,"ppg":1.33,"rpg":1,"apg":0,"spg":0.7,"bpg":0,"fgPct":66.7,"threePct":0,"ftPct":0},
  },
  {
    id: "samsung-096002",
    name: "최예슬",
    number: 21,
    position: "SF",
    height: "180cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096002.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":23,"mpg":11.4,"ppg":2.17,"rpg":1.6,"apg":0.6,"spg":0.3,"bpg":0,"fgPct":48.5,"threePct":21.4,"ftPct":90},
  },
  {
    id: "samsung-095904",
    name: "이예나",
    number: 23,
    position: "SF",
    height: "179cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095904.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":11,"mpg":6.2,"ppg":1.73,"rpg":0.9,"apg":0.2,"spg":0.2,"bpg":0,"fgPct":33.3,"threePct":20,"ftPct":0},
  },
  {
    id: "samsung-095115",
    name: "배혜윤",
    number: 25,
    position: "C",
    height: "183cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095115.png?ver=241016",
    bio: {
      birth_year: 1989,
      age: 37,
      career_year: 18,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "1옵션"],
    seasonStats: {"games":26,"mpg":24,"ppg":7.31,"rpg":3.8,"apg":3.4,"spg":0.5,"bpg":0.3,"fgPct":45.8,"threePct":0,"ftPct":90.6},
  },
  {
    id: "samsung-095497",
    name: "윤예빈",
    number: 32,
    position: "PG",
    height: "180cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095497.png?ver=241016",
    bio: {
      birth_year: 1997,
      age: 29,
      career_year: 10,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑"],
    seasonStats: {"games":26,"mpg":18.7,"ppg":5.08,"rpg":3.5,"apg":1.6,"spg":1,"bpg":0.4,"fgPct":45.9,"threePct":22.4,"ftPct":42.9},
  },
  {
    id: "samsung-095782",
    name: "방지온",
    number: 43,
    position: "C",
    height: "183cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095782.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":3,"mpg":2.7,"ppg":0,"rpg":0.3,"apg":0,"spg":0.3,"bpg":0.3,"fgPct":0,"threePct":0,"ftPct":0},
  },
  {
    id: "samsung-096027",
    name: "가와무라 미유키",
    number: 45,
    position: "C",
    height: "185cm",
    team: "삼성생명 블루밍스",
    teamId: "samsung",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096027.png?ver=241016",
    bio: {
      birth_year: 1994,
      age: 32,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["흐름 체인저"],
    seasonStats: {"games":24,"mpg":14.7,"ppg":4.5,"rpg":1.7,"apg":0.7,"spg":0.3,"bpg":0.1,"fgPct":43.9,"threePct":12.5,"ftPct":61.3},
  },
  // ─── BNK 썸 ───────────────────────────────────,
  {
    id: "bnk-095825",
    name: "심수현",
    number: 0,
    position: "PG",
    height: "165cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095825.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":17,"mpg":3.3,"ppg":0.47,"rpg":0.6,"apg":0.2,"spg":0,"bpg":0,"fgPct":12.5,"threePct":0,"ftPct":66.7},
  },
  {
    id: "bnk-095780",
    name: "변소정",
    number: 1,
    position: "SF",
    height: "180cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095780.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":30,"mpg":23.3,"ppg":5.03,"rpg":3.3,"apg":0.7,"spg":0.4,"bpg":0.3,"fgPct":46.5,"threePct":31.6,"ftPct":59.1},
  },
  {
    id: "bnk-095716",
    name: "최서연",
    number: 2,
    position: "PG",
    height: "170cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095716.png?ver=241016",
    bio: {
      birth_year: 2002,
      age: 24,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "bnk-095834",
    name: "김민아",
    number: 3,
    position: "PG",
    height: "170cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095834.png?ver=241016",
    bio: {
      birth_year: 2004,
      age: 22,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":12,"mpg":3.1,"ppg":0.58,"rpg":0.3,"apg":0.3,"spg":0.2,"bpg":0,"fgPct":28.6,"threePct":25,"ftPct":0},
  },
  {
    id: "bnk-096000",
    name: "김보현",
    number: 4,
    position: "PG",
    height: "174cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096000.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "bnk-095484",
    name: "안혜지",
    number: 5,
    position: "PG",
    height: "165cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095484.png?ver=241016",
    bio: {
      birth_year: 1997,
      age: 29,
      career_year: 11,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["베테랑", "국가대표", "1옵션", "폭발력", "플레이메이커"],
    seasonStats: {"games":30,"mpg":37.1,"ppg":11.17,"rpg":3.5,"apg":6.1,"spg":0.8,"bpg":0,"fgPct":35.4,"threePct":28.9,"ftPct":69.7},
  },
  {
    id: "bnk-095636",
    name: "이소희",
    number: 6,
    position: "PG",
    height: "171cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095636.png?ver=241016",
    bio: {
      birth_year: 2000,
      age: 26,
      career_year: 8,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["국가대표", "1옵션", "폭발력"],
    seasonStats: {"games":30,"mpg":35.2,"ppg":12.93,"rpg":3.8,"apg":2.3,"spg":0.6,"bpg":0.1,"fgPct":38.9,"threePct":34.9,"ftPct":86},
  },
  {
    id: "bnk-095186",
    name: "박혜진",
    number: 7,
    position: "PG",
    height: "179cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095186.png?ver=241016",
    bio: {
      birth_year: 1990,
      age: 36,
      career_year: 17,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["베테랑", "국가대표", "1옵션", "수비형", "슈터", "리바운더"],
    seasonStats: {"games":30,"mpg":35,"ppg":9.8,"rpg":6.5,"apg":2.5,"spg":1.2,"bpg":0.5,"fgPct":37.2,"threePct":37.4,"ftPct":87.1},
  },
  {
    id: "bnk-096135",
    name: "이원정",
    number: 8,
    position: "PG",
    height: "172cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096135.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":17,"mpg":6.7,"ppg":1.12,"rpg":0.9,"apg":0.2,"spg":0.1,"bpg":0.1,"fgPct":33.3,"threePct":0,"ftPct":100},
  },
  {
    id: "bnk-095900",
    name: "박다원",
    number: 9,
    position: "SF",
    height: "179cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095900.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":1.3,"ppg":0,"rpg":1,"apg":1,"spg":0,"bpg":0,"fgPct":0,"threePct":0,"ftPct":0},
  },
  {
    id: "bnk-095784",
    name: "최민주",
    number: 10,
    position: "C",
    height: "180cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095784.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":1.9,"ppg":2,"rpg":2,"apg":0,"spg":0,"bpg":0,"fgPct":100,"threePct":0,"ftPct":0},
  },
  {
    id: "bnk-095899",
    name: "김정은",
    number: 11,
    position: "SF",
    height: "177cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095899.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":30,"mpg":15.8,"ppg":3.6,"rpg":2.2,"apg":0.7,"spg":0.2,"bpg":0.2,"fgPct":39.1,"threePct":32.5,"ftPct":62.5},
  },
  {
    id: "bnk-096001",
    name: "김도연",
    number: 12,
    position: "C",
    height: "186cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096001.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":20,"mpg":8.9,"ppg":1.75,"rpg":1.7,"apg":0.2,"spg":0.2,"bpg":0.6,"fgPct":28.3,"threePct":0,"ftPct":56.3},
  },
  {
    id: "bnk-096136",
    name: "박지수",
    number: 13,
    position: "SF",
    height: "177cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096136.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":1,"mpg":0.6,"ppg":0,"rpg":0,"apg":0,"spg":0,"bpg":0,"fgPct":0,"threePct":0,"ftPct":0},
  },
  {
    id: "bnk-095833",
    name: "박성진",
    number: 15,
    position: "C",
    height: "184cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095833.png?ver=241016",
    bio: {
      birth_year: 2004,
      age: 22,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":21,"mpg":7.6,"ppg":0.81,"rpg":1.3,"apg":0.2,"spg":0.3,"bpg":0.2,"fgPct":28,"threePct":0,"ftPct":100},
  },
  {
    id: "bnk-095248",
    name: "김소니아",
    number: 24,
    position: "SF",
    height: "178cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095248.png?ver=241016",
    bio: {
      birth_year: 1993,
      age: 33,
      career_year: 1,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["국가대표", "에이스", "폭발력", "수비형", "리바운더", "골밑 핵심"],
    seasonStats: {"games":30,"mpg":32.6,"ppg":14.87,"rpg":9.1,"apg":2.6,"spg":1.2,"bpg":0.4,"fgPct":46.6,"threePct":23,"ftPct":83.2},
  },
  {
    id: "bnk-095919",
    name: "스나가와 나츠키",
    number: 30,
    position: "PG",
    height: "162cm",
    team: "BNK 썸",
    teamId: "bnk",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095919.png?ver=241016",
    bio: {
      birth_year: 1995,
      age: 31,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["슈터"],
    seasonStats: {"games":25,"mpg":8.2,"ppg":2.88,"rpg":1.4,"apg":0.3,"spg":0.3,"bpg":0,"fgPct":36.1,"threePct":38.7,"ftPct":90.9},
  },
  // ─── KB 스타즈 ──────────────────────────────────,
  {
    id: "kb-095781",
    name: "김은선",
    number: 1,
    position: "PG",
    height: "169cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095781.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "kb-095710",
    name: "허예은",
    number: 2,
    position: "PG",
    height: "165cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095710.png?ver=241016",
    bio: {
      birth_year: 2001,
      age: 25,
      career_year: 7,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["국가대표", "1옵션", "폭발력", "수비형", "슈터", "플레이메이커"],
    seasonStats: {"games":30,"mpg":33.5,"ppg":11.6,"rpg":4.4,"apg":6.7,"spg":1.3,"bpg":0.1,"fgPct":45,"threePct":37.3,"ftPct":87.8},
  },
  {
    id: "kb-095637",
    name: "이채은",
    number: 3,
    position: "PG",
    height: "171cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095637.png?ver=241016",
    bio: {
      birth_year: 2000,
      age: 26,
      career_year: 8,
      national_team: { is_national: true, level: "국가대표 후보" },
    },
    tags: ["국가대표", "수비형", "슈터", "안정감"],
    seasonStats: {"games":30,"mpg":27.2,"ppg":8.43,"rpg":2.9,"apg":1.4,"spg":1.3,"bpg":0.1,"fgPct":48.5,"threePct":38.6,"ftPct":90},
  },
  {
    id: "kb-095037",
    name: "염윤아",
    number: 4,
    position: "PG",
    height: "177cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095037.png?ver=241016",
    bio: {
      birth_year: 1987,
      age: 39,
      career_year: 20,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑"],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "kb-095746",
    name: "양지수",
    number: 5,
    position: "SF",
    height: "174cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095746.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 6,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["슈터"],
    seasonStats: {"games":30,"mpg":12.9,"ppg":2.17,"rpg":1.6,"apg":0.4,"spg":0.5,"bpg":0,"fgPct":29,"threePct":35,"ftPct":55.6},
  },
  {
    id: "kb-095642",
    name: "이윤미",
    number: 6,
    position: "SF",
    height: "172cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095642.png?ver=241016",
    bio: {
      birth_year: 2000,
      age: 26,
      career_year: 8,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":3,"mpg":4.8,"ppg":1,"rpg":1.3,"apg":0,"spg":0,"bpg":0,"fgPct":0,"threePct":50,"ftPct":0},
  },
  {
    id: "kb-095533",
    name: "박지수",
    number: 7,
    position: "C",
    height: "193cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095533.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 9,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["국가대표", "에이스", "폭발력", "슈터", "리바운더", "골밑 핵심"],
    seasonStats: {"games":24,"mpg":23.4,"ppg":16.54,"rpg":10.1,"apg":2.6,"spg":0.7,"bpg":1.7,"fgPct":60.2,"threePct":46.2,"ftPct":64},
  },
  {
    id: "kb-095251",
    name: "김민정",
    number: 8,
    position: "SF",
    height: "181cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095251.png?ver=241016",
    bio: {
      birth_year: 1994,
      age: 32,
      career_year: 13,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑"],
    seasonStats: {"games":2,"mpg":4,"ppg":1,"rpg":1.5,"apg":0.5,"spg":0,"bpg":0,"fgPct":33.3,"threePct":0,"ftPct":0},
  },
  {
    id: "kb-095836",
    name: "노혜경",
    number: 9,
    position: "SF",
    height: "178cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095836.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "kb-095263",
    name: "강이슬",
    number: 11,
    position: "SF",
    height: "180cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095263.png?ver=241016",
    bio: {
      birth_year: 1994,
      age: 32,
      career_year: 13,
      national_team: { is_national: true, level: "A대표팀" },
    },
    tags: ["베테랑", "국가대표", "에이스", "폭발력", "슈터", "리바운더"],
    seasonStats: {"games":29,"mpg":32.9,"ppg":15.55,"rpg":6.6,"apg":3.1,"spg":0.9,"bpg":0.3,"fgPct":49.2,"threePct":35.8,"ftPct":68.2},
  },
  {
    id: "kb-095999",
    name: "송윤하",
    number: 14,
    position: "C",
    height: "179cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095999.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":30,"mpg":19.6,"ppg":7.03,"rpg":4.1,"apg":1.1,"spg":0.6,"bpg":1.1,"fgPct":47.5,"threePct":31.3,"ftPct":96},
  },
  {
    id: "kb-096137",
    name: "김민경",
    number: 15,
    position: "C",
    height: "183cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096137.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "kb-095901",
    name: "고현지",
    number: 17,
    position: "SF",
    height: "182cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095901.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":10,"mpg":2.5,"ppg":0.7,"rpg":0.8,"apg":0.2,"spg":0.1,"bpg":0.1,"fgPct":25,"threePct":25,"ftPct":0},
  },
  {
    id: "kb-095978",
    name: "이여명",
    number: 19,
    position: "PG",
    height: "162cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095978.png?ver=241016",
    bio: {
      birth_year: 2001,
      age: 25,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":10,"mpg":1.9,"ppg":0.4,"rpg":0.1,"apg":0.2,"spg":0.2,"bpg":0,"fgPct":28.6,"threePct":0,"ftPct":0},
  },
  {
    id: "kb-095902",
    name: "성수연",
    number: 22,
    position: "PG",
    height: "165cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095902.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":29,"mpg":9.7,"ppg":1.62,"rpg":1.3,"apg":1.3,"spg":0.3,"bpg":0.2,"fgPct":34.9,"threePct":10,"ftPct":47.1},
  },
  {
    id: "kb-096138",
    name: "고리미",
    number: 24,
    position: "SF",
    height: "175cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096138.png?ver=241016",
    bio: {
      birth_year: 2001,
      age: 25,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":8,"mpg":2,"ppg":0.75,"rpg":0.4,"apg":0,"spg":0,"bpg":0,"fgPct":42.9,"threePct":0,"ftPct":0},
  },
  {
    id: "kb-095543",
    name: "나윤정",
    number: 38,
    position: "SF",
    height: "172cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095543.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 9,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
    seasonStats: {"games":29,"mpg":15.6,"ppg":5,"rpg":1.8,"apg":0.7,"spg":0.5,"bpg":0.1,"fgPct":42.6,"threePct":24.6,"ftPct":85.7},
  },
  {
    id: "kb-096033",
    name: "사카이 사라",
    number: 55,
    position: "PG",
    height: "164cm",
    team: "KB 스타즈",
    teamId: "kb",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096033.png?ver=241016",
    bio: {
      birth_year: 1995,
      age: 31,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["수비형", "안정감"],
    seasonStats: {"games":30,"mpg":29.1,"ppg":7.03,"rpg":3.4,"apg":2.7,"spg":1.3,"bpg":0,"fgPct":34.2,"threePct":31,"ftPct":88.9},
  },
  // ─── 신한은행 ────────────────────────────────────,
  {
    id: "shinhan-095633",
    name: "신이슬",
    number: 1,
    position: "PG",
    height: "170cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095633.png?ver=241016",
    bio: {
      birth_year: 2000,
      age: 26,
      career_year: 8,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["에이스", "폭발력", "수비형"],
    seasonStats: {"games":30,"mpg":34.4,"ppg":12.73,"rpg":5.1,"apg":2.6,"spg":1.3,"bpg":0.4,"fgPct":41.6,"threePct":30.6,"ftPct":76.7},
  },
  {
    id: "shinhan-096141",
    name: "정채련",
    number: 2,
    position: "PG",
    height: "161cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096141.png?ver=241016",
    bio: {
      birth_year: 2003,
      age: 23,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":7,"mpg":1.8,"ppg":0.57,"rpg":0.4,"apg":0.7,"spg":0.3,"bpg":0,"fgPct":40,"threePct":0,"ftPct":0},
  },
  {
    id: "shinhan-095527",
    name: "이혜미",
    number: 4,
    position: "PG",
    height: "170cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095527.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 9,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":16,"mpg":8.7,"ppg":2.5,"rpg":1.4,"apg":0.3,"spg":0.3,"bpg":0.1,"fgPct":57.1,"threePct":29.6,"ftPct":88.9},
  },
  {
    id: "shinhan-096142",
    name: "황현정",
    number: 5,
    position: "PG",
    height: "170cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096142.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":null,"mpg":null,"ppg":null,"rpg":null,"apg":null,"spg":null,"bpg":null,"fgPct":null,"threePct":null,"ftPct":null},
  },
  {
    id: "shinhan-095261",
    name: "최이샘",
    number: 6,
    position: "SF",
    height: "182cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095261.png?ver=241016",
    bio: {
      birth_year: 1994,
      age: 32,
      career_year: 13,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "안정감"],
    seasonStats: {"games":29,"mpg":20.3,"ppg":4.66,"rpg":5.2,"apg":1.3,"spg":0.3,"bpg":0.2,"fgPct":32,"threePct":31.7,"ftPct":100},
  },
  {
    id: "shinhan-095441",
    name: "신지현",
    number: 7,
    position: "PG",
    height: "174cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095441.png?ver=241016",
    bio: {
      birth_year: 1995,
      age: 31,
      career_year: 12,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "1옵션", "플레이메이커"],
    seasonStats: {"games":30,"mpg":26.4,"ppg":9.57,"rpg":3.8,"apg":3.8,"spg":0.6,"bpg":0.2,"fgPct":38.6,"threePct":26.5,"ftPct":84.7},
  },
  {
    id: "shinhan-095503",
    name: "김지영",
    number: 8,
    position: "PG",
    height: "172cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095503.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 10,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "식스맨", "플레이메이커", "흐름 체인저"],
    seasonStats: {"games":21,"mpg":27.1,"ppg":5.05,"rpg":4.6,"apg":4.5,"spg":0.3,"bpg":0.3,"fgPct":34.2,"threePct":17.3,"ftPct":67.6},
  },
  {
    id: "shinhan-095700",
    name: "고나연",
    number: 9,
    position: "SF",
    height: "173cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095700.png?ver=241016",
    bio: {
      birth_year: 2001,
      age: 25,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":24,"mpg":11.9,"ppg":2.79,"rpg":1.3,"apg":0.6,"spg":0.2,"bpg":0,"fgPct":22.6,"threePct":29.1,"ftPct":83.3},
  },
  {
    id: "shinhan-095826",
    name: "이두나",
    number: 10,
    position: "SF",
    height: "173cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095826.png?ver=241016",
    bio: {
      birth_year: 2004,
      age: 22,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":5,"mpg":8.1,"ppg":1,"rpg":0.8,"apg":0.2,"spg":0,"bpg":0,"fgPct":25,"threePct":0,"ftPct":50},
  },
  {
    id: "shinhan-095905",
    name: "허유정",
    number: 11,
    position: "PG",
    height: "173cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095905.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":2,"mpg":3.1,"ppg":0,"rpg":1,"apg":0.5,"spg":0,"bpg":0,"fgPct":0,"threePct":0,"ftPct":0},
  },
  {
    id: "shinhan-096143",
    name: "이가현",
    number: 17,
    position: "SF",
    height: "180cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096143.png?ver=241016",
    bio: {
      birth_year: 2007,
      age: 19,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":11,"mpg":3.2,"ppg":0.91,"rpg":0.3,"apg":0.1,"spg":0,"bpg":0,"fgPct":60,"threePct":25,"ftPct":33.3},
  },
  {
    id: "shinhan-095482",
    name: "김진영",
    number: 21,
    position: "SF",
    height: "177cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095482.png?ver=241016",
    bio: {
      birth_year: 1996,
      age: 30,
      career_year: 11,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["베테랑", "안정감"],
    seasonStats: {"games":29,"mpg":23.3,"ppg":6.24,"rpg":5.6,"apg":1.8,"spg":0.5,"bpg":0.4,"fgPct":42,"threePct":29.7,"ftPct":39.5},
  },
  {
    id: "shinhan-095972",
    name: "홍유순",
    number: 23,
    position: "SF",
    height: "179cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095972.png?ver=241016",
    bio: {
      birth_year: 2005,
      age: 21,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["1옵션"],
    seasonStats: {"games":30,"mpg":31.6,"ppg":9.3,"rpg":6.1,"apg":1.9,"spg":0.8,"bpg":0.3,"fgPct":46.4,"threePct":30,"ftPct":71.8},
  },
  {
    id: "shinhan-096029",
    name: "미마 루이",
    number: 25,
    position: "C",
    height: "185cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096029.png?ver=241016",
    bio: {
      birth_year: 1999,
      age: 27,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["1옵션", "폭발력", "골밑 핵심"],
    seasonStats: {"games":27,"mpg":24.4,"ppg":10.48,"rpg":5.3,"apg":1.1,"spg":0.8,"bpg":0.1,"fgPct":64.2,"threePct":24.6,"ftPct":68.1},
  },
  {
    id: "shinhan-095915",
    name: "히라노 미츠키",
    number: 33,
    position: "PG",
    height: "166cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_095915.png?ver=241016",
    bio: {
      birth_year: 1998,
      age: 28,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["흐름 체인저"],
    seasonStats: {"games":20,"mpg":14.1,"ppg":4.2,"rpg":1.7,"apg":2.4,"spg":0.5,"bpg":0,"fgPct":41.7,"threePct":22.2,"ftPct":66.7},
  },
  {
    id: "shinhan-096004",
    name: "김채은",
    number: 88,
    position: "C",
    height: "186cm",
    team: "신한은행 에스버드",
    teamId: "shinhan",
    imageUrl: "https://www.wkbl.or.kr/static/images/player/pimg/np_096004.png?ver=241016",
    bio: {
      birth_year: 2006,
      age: 20,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: [],
    seasonStats: {"games":6,"mpg":2.5,"ppg":2,"rpg":0.8,"apg":0,"spg":0,"bpg":0.2,"fgPct":83.3,"threePct":0,"ftPct":100},
  },
];

export const TAG_COLORS: Record<string, string> = {
  에이스: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
  "1옵션": "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400",
  식스맨: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400",
  리더: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
  수비형: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
  슈터: "bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-400",
  플레이메이커: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400",
  리바운더: "bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-400",
  클러치: "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-400",
  "흐름 체인저": "bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400",
  안정감: "bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-400",
  폭발력: "bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-900/30 dark:text-fuchsia-400",
  국가대표: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
  신인왕: "bg-lime-100 text-lime-700 dark:bg-lime-900/30 dark:text-lime-400",
  MVP: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400",
  베테랑: "bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400",
  "골밑 핵심": "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
};
