import type { Player } from "./types";

export interface WKBLTeam {
  id: string;
  name: string;
  shortName: string;
  color: string;
  rank: number;
  summary: string;
  league: "WKBL" | "KBL";
}

export const TEAMS: WKBLTeam[] = [
  // ─── WKBL 여자농구 ────────────────────────────────────────
  { id: "woori",   name: "우리은행 우리WON",     shortName: "우리은행",  color: "#003DA5", rank: 1, summary: "리그 최강 수비 조직력",       league: "WKBL" },
  { id: "hana",    name: "하나원큐",              shortName: "하나원큐",  color: "#007B5F", rank: 2, summary: "공격 밸런스 좋은 상승세 팀",  league: "WKBL" },
  { id: "samsung", name: "삼성생명 블루밍스",     shortName: "삼성생명",  color: "#1428A0", rank: 3, summary: "수비 중심 조직력 팀",         league: "WKBL" },
  { id: "bnk",     name: "BNK 썸",                shortName: "BNK",       color: "#E31837", rank: 4, summary: "빠른 템포 역습 농구",         league: "WKBL" },
  { id: "kb",      name: "KB 스타즈",             shortName: "KB",        color: "#CB9E00", rank: 5, summary: "재건 중인 전통 강호",         league: "WKBL" },
  { id: "shinhan", name: "신한은행 에스버드",      shortName: "신한은행",  color: "#0046FF", rank: 6, summary: "젊은 선수 중심 팀",          league: "WKBL" },
  // ─── KBL 남자농구 ─────────────────────────────────────────
  { id: "sono",    name: "고양 소노 스카이거너스", shortName: "소노",      color: "#0B3D91", rank: 1, summary: "라건아 중심 압도적 골밑 농구", league: "KBL" },
  { id: "db",      name: "원주 DB 프로미",         shortName: "DB",        color: "#FF6B00", rank: 2, summary: "빠른 공수 전환과 팀 조직력",  league: "KBL" },
  { id: "sk",      name: "서울 SK 나이츠",         shortName: "SK",        color: "#E31837", rank: 3, summary: "허훈 중심 화려한 공격농구",   league: "KBL" },
  { id: "mobis",   name: "울산 현대모비스 피버스",  shortName: "모비스",    color: "#003DA5", rank: 4, summary: "전통의 강호, 탄탄한 수비",   league: "KBL" },
  { id: "kt",      name: "수원 KT 소닉붐",         shortName: "KT",        color: "#D10000", rank: 5, summary: "빠른 트랜지션 농구",         league: "KBL" },
  { id: "lg",      name: "창원 LG 세이커스",       shortName: "LG",        color: "#A50034", rank: 6, summary: "리빌딩 중인 전통 강호",       league: "KBL" },
];

export const PLAYERS: Player[] = [
  // ─── 하나금융 ──────────────────────────────────────────
  {
    id: "hana-0",
    name: "하지윤",
    number: 0,
    position: "PG",
    height: "168cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100938359631.png",
    bio: {
      birth_year: 2000,
      age: 25,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["플레이메이커"],
  },
  {
    id: "hana-1",
    name: "박소회",
    number: 1,
    position: "PG",
    height: "168cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100941061481.png",
    bio: {
      birth_year: 1997,
      age: 28,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감"],
  },
  {
    id: "hana-2",
    name: "황윤서",
    number: 2,
    position: "SG",
    height: "170cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100930218651.png",
    bio: {
      birth_year: 2003,
      age: 22,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["슈터", "폭발력"],
  },
  {
    id: "hana-3",
    name: "정현",
    number: 3,
    position: "SF",
    height: "175cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100942053541.png",
    bio: {
      birth_year: 1998,
      age: 27,
      career_year: 6,
      national_team: {
        is_national: true,
        years: "2022~",
        level: "국가대표 후보",
      },
    },
    tags: ["국가대표", "수비형"],
  },
  {
    id: "hana-5",
    name: "고서연",
    number: 5,
    position: "C",
    height: "185cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100944509701.png",
    bio: {
      birth_year: 1999,
      age: 26,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["리바운더", "골밑 핵심"],
  },
  {
    id: "hana-6",
    name: "이은서",
    number: 6,
    position: "SF",
    height: "178cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100946270091.png",
    bio: {
      birth_year: 2001,
      age: 24,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["흐름 체인저"],
  },
  {
    id: "hana-7",
    name: "정예림",
    number: 7,
    position: "SG",
    height: "172cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100947351921.png",
    bio: {
      birth_year: 2000,
      age: 25,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["슈터"],
  },
  {
    id: "hana-9",
    name: "김시온",
    number: 9,
    position: "PG",
    height: "166cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100948330211.png",
    bio: {
      birth_year: 2004,
      age: 21,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["폭발력"],
  },
  {
    id: "hana-11",
    name: "양인영",
    number: 11,
    position: "SF",
    height: "176cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100949190291.png",
    bio: {
      birth_year: 1996,
      age: 29,
      career_year: 8,
      national_team: {
        is_national: true,
        years: "2018~2023",
        level: "A대표팀",
      },
    },
    tags: ["국가대표", "에이스", "클러치"],
  },
  {
    id: "hana-12",
    name: "김연진",
    number: 12,
    position: "PF",
    height: "183cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100950168871.png",
    bio: {
      birth_year: 1995,
      age: 30,
      career_year: 10,
      national_team: {
        is_national: true,
        years: "2017~2024",
        level: "A대표팀",
      },
    },
    tags: ["국가대표", "MVP", "리바운더", "베테랑"],
  },
  {
    id: "hana-13",
    name: "김정은",
    number: 13,
    position: "C",
    height: "188cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100951084211.png",
    bio: {
      birth_year: 1993,
      age: 32,
      career_year: 12,
      national_team: {
        is_national: true,
        years: "2013~2023",
        level: "A대표팀",
      },
    },
    tags: ["국가대표", "에이스", "베테랑", "골밑 핵심"],
  },
  {
    id: "hana-21",
    name: "사키",
    number: 21,
    position: "PF",
    height: "185cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100952428881.png",
    bio: {
      birth_year: 1998,
      age: 27,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["리바운더", "1옵션"],
  },
  {
    id: "hana-22",
    name: "이다현",
    number: 22,
    position: "SG",
    height: "170cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100953382431.png",
    bio: {
      birth_year: 2002,
      age: 23,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["슈터"],
  },
  {
    id: "hana-23",
    name: "박진영",
    number: 23,
    position: "SF",
    height: "177cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100954300501.png",
    bio: {
      birth_year: 1999,
      age: 26,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["수비형", "안정감"],
  },
  {
    id: "hana-31",
    name: "진안",
    number: 31,
    position: "C",
    height: "185cm",
    team: "하나금융",
    teamId: "hana",
    imageUrl:
      "http://www.hanafnbasketball.com/html/upload/Player/Player_202510100955464571.png",
    bio: {
      birth_year: 1996,
      age: 29,
      career_year: 8,
      national_team: {
        is_national: true,
        years: "2018~2024",
        level: "A대표팀",
      },
    },
    tags: ["국가대표", "골밑 핵심", "리바운더"],
  },

  // ─── 삼성블루밍스 ─────────────────────────────────────
  {
    id: "samsung-1",
    name: "하마니시 나나미",
    number: 1,
    position: "PG",
    height: "166cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=07908aec-5757-4c6b-a6c9-3561b9df4502",
    bio: {
      birth_year: 1999,
      age: 26,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["플레이메이커", "폭발력"],
  },
  {
    id: "samsung-2",
    name: "이해란",
    number: 2,
    position: "SG",
    height: "171cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=efdad702-fd74-4c45-ae7f-fde6aa02e85f",
    bio: {
      birth_year: 1997,
      age: 28,
      career_year: 7,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["수비형", "안정감"],
  },
  {
    id: "samsung-3",
    name: "조수아",
    number: 3,
    position: "SF",
    height: "176cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=00099332-75fa-4ca9-89d5-725ff7f1b79c",
    bio: {
      birth_year: 1998,
      age: 27,
      career_year: 6,
      national_team: {
        is_national: true,
        years: "2021~",
        level: "국가대표 후보",
      },
    },
    tags: ["국가대표", "슈터"],
  },
  {
    id: "samsung-7",
    name: "강유림",
    number: 7,
    position: "PF",
    height: "181cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl: null,
    bio: {
      birth_year: 2001,
      age: 24,
      career_year: 3,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["리바운더"],
  },
  {
    id: "samsung-8",
    name: "이주연",
    number: 8,
    position: "PG",
    height: "168cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=b0549b9d-25c8-4add-9cf7-4d51f6ce7dff",
    bio: {
      birth_year: 2000,
      age: 25,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["플레이메이커"],
  },
  {
    id: "samsung-10",
    name: "양혜은",
    number: 10,
    position: "SF",
    height: "174cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=108d2ef1-3d67-444b-abfd-3b72fccae90e",
    bio: {
      birth_year: 1994,
      age: 31,
      career_year: 10,
      national_team: {
        is_national: true,
        years: "2016~2023",
        level: "A대표팀",
      },
    },
    tags: ["국가대표", "베테랑", "에이스"],
  },
  {
    id: "samsung-13",
    name: "김단비",
    number: 13,
    position: "SG",
    height: "174cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=0c7e0902-d569-4d60-aae9-5a8a91dffff6",
    bio: {
      birth_year: 1992,
      age: 33,
      career_year: 14,
      national_team: {
        is_national: true,
        years: "2012~2024",
        level: "A대표팀",
      },
    },
    tags: ["국가대표", "MVP", "에이스", "클러치", "베테랑"],
  },
  {
    id: "samsung-16",
    name: "임규리",
    number: 16,
    position: "C",
    height: "186cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=770d410e-8045-4f4a-abad-1694e11a3f0f",
    bio: {
      birth_year: 1997,
      age: 28,
      career_year: 7,
      national_team: {
        is_national: true,
        years: "2020~",
        level: "A대표팀",
      },
    },
    tags: ["국가대표", "골밑 핵심", "리바운더"],
  },
  {
    id: "samsung-21",
    name: "최예슬",
    number: 21,
    position: "SF",
    height: "177cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=124ad457-5ad2-4308-aa12-3a78dc6bcd62",
    bio: {
      birth_year: 1999,
      age: 26,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["수비형", "흐름 체인저"],
  },
  {
    id: "samsung-25",
    name: "배혜윤",
    number: 25,
    position: "PF",
    height: "180cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=10e880d8-37c8-4ce2-991e-88ac615f6090",
    bio: {
      birth_year: 1996,
      age: 29,
      career_year: 8,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["안정감", "리바운더"],
  },
  {
    id: "samsung-32",
    name: "윤예빈",
    number: 32,
    position: "C",
    height: "184cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=0bc54646-1f38-4a57-8487-70eb3447a825",
    bio: {
      birth_year: 2002,
      age: 23,
      career_year: 2,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["골밑 핵심"],
  },
  {
    id: "samsung-43",
    name: "방지온",
    number: 43,
    position: "PF",
    height: "183cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=e7c4811e-a66d-4982-97c4-e0c5961e6c5f",
    bio: {
      birth_year: 2003,
      age: 22,
      career_year: 1,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["폭발력"],
  },
  {
    id: "samsung-45",
    name: "가와무라 미유키",
    number: 45,
    position: "C",
    height: "190cm",
    team: "삼성블루밍스",
    teamId: "samsung",
    imageUrl:
      "http://www.samsungblueminx.com/function/image_stream.jsp?path=player&filename=b7070dd2-227d-4b0d-86ed-4dfe5e97e895",
    bio: {
      birth_year: 1997,
      age: 28,
      career_year: 6,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["1옵션", "리바운더", "골밑 핵심"],
  },

  // ─── 고양 소노 스카이거너스 (KBL) ────────────────────────
  {
    id: "sono-14",
    name: "라건아",
    number: 14,
    position: "C",
    height: "207cm",
    team: "고양 소노 스카이거너스",
    teamId: "sono",
    imageUrl: null,
    bio: {
      birth_year: 1990,
      age: 35,
      career_year: 9,
      national_team: { is_national: true, years: "2021~", level: "A대표팀" },
    },
    tags: ["에이스", "골밑 핵심", "리바운더", "국가대표"],
  },
  {
    id: "sono-4",
    name: "최성모",
    number: 4,
    position: "PG",
    height: "185cm",
    team: "고양 소노 스카이거너스",
    teamId: "sono",
    imageUrl: null,
    bio: {
      birth_year: 1991,
      age: 34,
      career_year: 11,
      national_team: { is_national: true, years: "2015~2022", level: "A대표팀" },
    },
    tags: ["플레이메이커", "안정감", "베테랑", "국가대표"],
  },
  {
    id: "sono-24",
    name: "이원준",
    number: 24,
    position: "SG",
    height: "193cm",
    team: "고양 소노 스카이거너스",
    teamId: "sono",
    imageUrl: null,
    bio: {
      birth_year: 1998,
      age: 27,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["슈터", "폭발력"],
  },
  {
    id: "sono-2",
    name: "이현중",
    number: 2,
    position: "SF",
    height: "196cm",
    team: "고양 소노 스카이거너스",
    teamId: "sono",
    imageUrl: null,
    bio: {
      birth_year: 2001,
      age: 24,
      career_year: 3,
      national_team: { is_national: true, years: "2023~", level: "국가대표 후보" },
    },
    tags: ["수비형", "흐름 체인저", "국가대표"],
  },
  {
    id: "sono-23",
    name: "박지훈",
    number: 23,
    position: "PF",
    height: "201cm",
    team: "고양 소노 스카이거너스",
    teamId: "sono",
    imageUrl: null,
    bio: {
      birth_year: 1997,
      age: 28,
      career_year: 6,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["리바운더", "안정감"],
  },

  // ─── 원주 DB 프로미 (KBL) ────────────────────────────────
  {
    id: "db-11",
    name: "이선재",
    number: 11,
    position: "SG",
    height: "191cm",
    team: "원주 DB 프로미",
    teamId: "db",
    imageUrl: null,
    bio: {
      birth_year: 1996,
      age: 29,
      career_year: 7,
      national_team: { is_national: true, years: "2022~", level: "A대표팀" },
    },
    tags: ["에이스", "슈터", "클러치", "국가대표"],
  },
  {
    id: "db-3",
    name: "강상재",
    number: 3,
    position: "PG",
    height: "187cm",
    team: "원주 DB 프로미",
    teamId: "db",
    imageUrl: null,
    bio: {
      birth_year: 1993,
      age: 32,
      career_year: 10,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["플레이메이커", "베테랑", "안정감"],
  },
  {
    id: "db-5",
    name: "홍준표",
    number: 5,
    position: "PF",
    height: "203cm",
    team: "원주 DB 프로미",
    teamId: "db",
    imageUrl: null,
    bio: {
      birth_year: 1999,
      age: 26,
      career_year: 5,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["리바운더", "골밑 핵심"],
  },
  {
    id: "db-21",
    name: "김준일",
    number: 21,
    position: "SF",
    height: "197cm",
    team: "원주 DB 프로미",
    teamId: "db",
    imageUrl: null,
    bio: {
      birth_year: 2000,
      age: 25,
      career_year: 4,
      national_team: { is_national: false, level: "없음" },
    },
    tags: ["수비형", "흐름 체인저"],
  },
  {
    id: "db-33",
    name: "윤호영",
    number: 33,
    position: "C",
    height: "205cm",
    team: "원주 DB 프로미",
    teamId: "db",
    imageUrl: null,
    bio: {
      birth_year: 1988,
      age: 37,
      career_year: 15,
      national_team: { is_national: true, years: "2010~2021", level: "A대표팀" },
    },
    tags: ["베테랑", "골밑 핵심", "리바운더", "국가대표"],
  },
];

export const TAG_COLORS: Record<string, string> = {
  에이스: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
  "1옵션": "bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400",
  식스맨: "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400",
  리더: "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
  수비형: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
  슈터: "bg-sky-100 text-sky-700 dark:bg-sky-900/30 dark:text-sky-400",
  플레이메이커: "bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400",
  리바운더: "bg-violet-100 text-violet-700 dark:bg-violet-900/30 dark:text-violet-400",
  클러치: "bg-rose-100 text-rose-700 dark:bg-rose-900/30 dark:text-rose-400",
  "흐름 체인저": "bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400",
  안정감: "bg-teal-100 text-teal-700 dark:bg-teal-900/30 dark:text-teal-400",
  폭발력: "bg-fuchsia-100 text-fuchsia-700 dark:bg-fuchsia-900/30 dark:text-fuchsia-400",
  국가대표: "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
  신인왕: "bg-lime-100 text-lime-700 dark:bg-lime-900/30 dark:text-lime-400",
  MVP: "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400",
  베테랑: "bg-zinc-100 text-zinc-600 dark:bg-zinc-800 dark:text-zinc-400",
  "골밑 핵심": "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
};
